spring:
  application:
    name: emall-api-gateway
server:
  port: 8888
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:9527/eureka
logging:
  config: classpath:log4j2.xml
zuul:
  ignored-services: emall-service-ucenter
  routes:
    ucenter:
      path: /ucenter/**
      sensitiveHeaders:
      service-id: emall-web-ucenter
    authserver:
      path: /uaa/**
      sensitiveHeaders:
      service-id: emall-auth-server
      stripPrefix: false
    vue:
      path: /**
      url: http://localhost:8080/
  add-proxy-headers: true
security:
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://emall-auth-server/uaa/oauth/token
      userAuthorizationUri: http://localhost:7777/uaa/oauth/authorize
      clientId: client
      clientSecret: secret
    resource:
      user-info-uri:  http://localhost:7777/uaa/user
      prefer-token-info: false
ribbon:
  ReadTimeout: 30000
  SocketTimeout: 30000