spring:
  application:
    name: emall-api-gateway
  datasource:
    url:  jdbc:mysql://10.1.5.92:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 8888
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:9527/eureka
logging:
  config: classpath:log4j2.xml
zuul:
  ignored-services: emall-service-ucenter
  routes:
    ucenter:
      path: /ucenter/**
      service-id: emall-web-ucenter
security:
  oauth2:
    resource:
      filter-order: 3
ribbon:
  ReadTimeout: 30000
  SocketTimeout: 30000