DROP TABLE IF EXISTS `uc_user` ;

CREATE TABLE `uc_user` (
  id VARCHAR(36) NOT NULL ,
  avatar VARCHAR(50),
  username VARCHAR(20) NOT NULL ,
  phone VARCHAR(15) NOT NULL ,
  name VARCHAR(20),
  password VARCHAR(128) NOT NULL ,
  salt VARCHAR(60),
  birthday TIMESTAMP,
  sex INT,
  email VARCHAR(40),
  status INT NOT NULL DEFAULT 1,
  deleted INT NOT NULL DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  create_by VARCHAR(36),
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  update_by VARCHAR(36),
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE `uc_role` (
  id VARCHAR(36) NOT NULL ,
  name VARCHAR(20) NOT NULL ,
  value VARCHAR(15) NOT NULL ,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  create_by VARCHAR(36),
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  update_by VARCHAR(36),
  status INT NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE `uc_menu` (
  id VARCHAR(36) NOT NULL ,
  code VARCHAR(20) NOT NULL ,
  p_code VARCHAR(20),
  p_id VARCHAR(20),
  name VARCHAR(30) NOT NULL ,
  url VARCHAR(50) ,
  level INT NOT NULL ,
  sort int NOT NULL ,
  status INT NOT NULL DEFAULT 1,
  icon VARCHAR(20),
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;