spring:
  application:
    name: emall-hystrix-turbine
server:
  port: 7777
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9527/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
turbine:
  app-config: emall-web-ucenter
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: hystrix.stream
logging:
  config: classpath:log4j2.xml